name: Validate CSV Files

on:
  push:
  pull_request:

jobs:
  validate-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Validate CSV files
        run: |
          for file in output/*.csv; do
            if [ -f "$file" ]; then
              python .github/scripts/validate_csv.py "$file"
            fi
          done
